"""Subset-embed the repo's Noto Sans SC faces into a rendered presentation.

Consumed by render_pptx.render_deck via the manifest's fonts.embed token:

    "fonts": {"embed": {"face": "Noto Sans SC",
                        "regular": "../../fonts/NotoSansSC-Regular.ttf",
                        "bold": "../../fonts/NotoSansSC-Bold.ttf"}}

Character collection walks deck blocks (the renderer's own input, so it is
exactly the text any run can carry in the embedded face); font paths resolve
against the template directory, the same convention as source_pptx. Each
weight is subsetted to those characters with fonttools and wrapped as an
uncompressed Embedded OpenType (EOT v0x00020002, TTEMBED_SUBSET) part at
/ppt/fonts/fontN.fntdata. The fntdata part is EOT, not a bare TTF: PowerPoint
writes EOT itself and empirically ignores bare-TTF parts (verified against
PowerPoint 16.0 via a render A/B with an uninstalled face — raw TTF and a
first EOT attempt with offset-based name records were both ignored; the
spec-layout EOT below, byte-mirroring PowerPoint's own serialization
[NUL-terminated Family/Style names, empty RootString checksum 0x50475342,
EUDCCodePage 65001], is honored). The matching p:embeddedFontLst lands after
p:notesSz in presentation.xml (ECMA-376 child order) with
embedTrueTypeFonts/saveSubsetFonts flags on the root; python-pptx maps the
fntdata extension to application/x-fontdata natively, so [Content_Types].xml
gains a proper Default entry on save.

Degradation mirrors the MML2OMML.XSL pattern: without fonttools, with a
missing font file, or with no embeddable weights, embedding is skipped, the
typeface stays declared in the runs (they are written before this module
runs), and the caller receives the warning string to surface. Rendering
never fails here: subsetting runs to completion before any package part is
created, and render_pptx additionally catches any embedding exception into
the same warning channel.
"""
from __future__ import annotations

import io
import struct
from pathlib import Path
from xml.sax.saxutils import quoteattr

from pptx.opc.package import Part
from pptx.oxml import parse_xml
from pptx.oxml.ns import qn

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont

    HAS_FONTTOOLS = True
except ImportError:  # degrade, never hard-fail (see module docstring)
    subset = None
    TTFont = None
    HAS_FONTTOOLS = False

FONT_REL_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font"
FNTDATA_CONTENT_TYPE = "application/x-fontdata"

NS_P = "http://schemas.openxmlformats.org/presentationml/2006/main"
NS_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"

# text the renderer synthesizes instead of reading from the deck: the
# text-image list marker "- " and the page-number field's digits (the field
# value is generated by PowerPoint at render time)
SYNTHESIZED_CHARS = "- 0123456789"

# EOT metadata mirroring PowerPoint's own embedding of a Simplified Chinese
# face: GB2312_CHARSET; weights are OS/2.usWeightClass values
EOT_CHARSET = 134
WEIGHTS = {"regular": 400, "bold": 700}
WEIGHT_ELEMENTS = {"regular": "p:regular", "bold": "p:bold"}


def collect_deck_characters(deck: dict) -> set[str]:
    """Every character a rendered run can carry: block text/captions, list
    items, plus the renderer-synthesized list marker and page-number digits.
    Text is collected raw — emphasis **markers** stay in because the literal
    roles (caption, title) render them verbatim; a superset subset costs a
    byte, an under-subset breaks machines without the font."""
    chars = set(SYNTHESIZED_CHARS)
    for page in deck.get("pages", []):
        for block in page.get("blocks", []):
            for field in ("text", "caption"):
                if block.get(field):
                    chars.update(block[field])
            if block.get("items"):
                chars.update("".join(block["items"]))
    return chars


def subset_font_bytes(font_path: Path, characters: set[str]) -> bytes:
    """Full TTF -> subset TTF covering exactly `characters` (chars the font
    lacks, e.g. emoji, are dropped by the subsetter; PowerPoint falls back
    for those anyway). Name records are kept in full so the embedded font
    still answers to its family name."""
    opts = subset.Options()
    opts.name_IDs = ["*"]
    font = subset.load_font(str(font_path), opts)
    subsetter = subset.Subsetter(options=opts)
    subsetter.populate(text="".join(characters))
    subsetter.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    font.close()
    return buf.getvalue()


def wrap_eot(ttf: bytes, face: str, weight: int) -> bytes:
    """Subset TTF -> uncompressed EOT v0x00020002 (see module docstring for
    why the layout must byte-mirror PowerPoint's own serialization)."""
    font = TTFont(io.BytesIO(ttf), lazy=True)
    head, os2, name = font["head"], font["OS/2"], font["name"]
    panose = bytes(getattr(os2.panose, f) for f in (
        "bFamilyType", "bSerifStyle", "bWeight", "bProportion", "bContrast",
        "bStrokeVariation", "bArmStyle", "bLetterForm", "bMidline", "bXHeight"))
    version = name.getName(5, 3, 1, 0x409) or name.getName(5, 1, 0, 0)
    font.close()

    style = next(s for s, w in WEIGHTS.items() if w == weight).capitalize()
    names = [
        (face + "\0").encode("utf-16-le"),        # FamilyName (NUL-terminated)
        (style + "\0").encode("utf-16-le"),       # StyleName (NUL-terminated)
        str(version or "Version 1.000").encode("utf-16-le"),  # VersionName
        (face if weight == 400 else f"{face} {style}").encode("utf-16-le"),
        b"",                                       # RootString (empty)
    ]
    body = struct.pack(
        "<IIII", 0, len(ttf), 0x00020002, 0x1)  # EOTSize patched below
    body += panose + bytes((EOT_CHARSET, 0))
    body += struct.pack("<IHH", weight, os2.fsType, 0x504C)
    body += struct.pack("<IIII", os2.ulUnicodeRange1, os2.ulUnicodeRange2,
                        os2.ulUnicodeRange3, os2.ulUnicodeRange4)
    body += struct.pack("<II", os2.ulCodePageRange1 or 0,
                        os2.ulCodePageRange2 or 0)
    body += struct.pack("<I", head.checkSumAdjustment)
    body += struct.pack("<IIII", 0, 0, 0, 0)
    for encoded in names:
        body += struct.pack("<HH", 0, len(encoded)) + encoded
    body += struct.pack("<I", 0x50475342)  # RootStringCheckSum (empty string)
    body += struct.pack("<I", 65001)       # EUDCCodePage
    body += struct.pack("<HH", 0, 0)       # Padding6, SignatureSize
    body += struct.pack("<II", 0, 0)       # EUDCFlags, EUDCFontSize
    total = len(body) + len(ttf)
    return struct.pack("<I", total) + body[4:] + ttf


def _drop_existing_embed(prs) -> None:
    """Remove any earlier embeddedFontLst (and its font parts) so embedding
    twice on one Presentation stays package-clean."""
    pres = prs.part._element
    for lst in pres.findall(qn("p:embeddedFontLst")):
        for el in lst.iter():
            rid = el.get(qn("r:id"))
            if rid is not None and rid in prs.part.rels:
                prs.part.drop_rel(rid)
        pres.remove(lst)


def embed_fonts(prs, *, face: str, weights: dict[str, Path],
                characters: set[str], warn) -> dict | None:
    """Embed subsetted weights of `face` into a rendered Presentation.

    weights maps element names ("regular"/"bold") to font file paths. Returns
    a stats payload ({"face", "chars", "weights": {name: bytes}}) on success,
    or None after warn(reason) on any degrade condition.
    """
    if not HAS_FONTTOOLS:
        warn(f"fonttools not installed — {face!r} stays declared but is not "
             "embedded; machines without the font will substitute")
        return None
    if not weights:
        warn("fonts.embed declares no regular/bold weight; embedding skipped")
        return None
    missing = [str(p) for p in weights.values() if not Path(p).is_file()]
    if missing:
        warn(f"font file(s) missing, embedding skipped: {', '.join(missing)}")
        return None

    # build every payload before touching the package: a failure here (e.g.
    # corrupt font) must not leave stray parts behind
    # (WEIGHT_ELEMENTS iterates in ECMA-376 order: regular, bold)
    payloads = {name: wrap_eot(subset_font_bytes(Path(weights[name]), characters),
                               face, WEIGHTS[name])
                for name in WEIGHT_ELEMENTS if name in weights}

    package = prs.part.package
    _drop_existing_embed(prs)

    rids = {}
    sizes = {}
    for name, data in payloads.items():
        part = Part(package.next_partname("/ppt/fonts/font%d.fntdata"),
                    FNTDATA_CONTENT_TYPE, package, blob=data)
        rids[name] = prs.part.relate_to(part, FONT_REL_TYPE)
        sizes[name] = len(data)

    entries = "".join(
        f'<{WEIGHT_ELEMENTS[name]} r:id="{rids[name]}"/>'
        for name in WEIGHT_ELEMENTS if name in rids)
    lst = parse_xml(
        f'<p:embeddedFontLst xmlns:p="{NS_P}" xmlns:r="{NS_R}">'
        f"<p:embeddedFont>"
        f'<p:font typeface={quoteattr(face)} pitchFamily="34" charset="-122"/>'
        f"{entries}</p:embeddedFont></p:embeddedFontLst>")
    pres = prs.part._element
    # ECMA-376 order: embeddedFontLst sits after notesSz (before
    # defaultTextStyle); the template root always carries notesSz.
    pres.find(qn("p:notesSz")).addnext(lst)
    pres.set("embedTrueTypeFonts", "1")
    pres.set("saveSubsetFonts", "1")
    return {"face": face, "chars": len(characters), "weights": sizes}
